import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const defaultsDir = path.join(rootDir, "src", "prompts", "defaults");
const overridesDir = path.join(rootDir, "src", "prompts", "overrides");
const outputPath = path.join(rootDir, "src", "prompts", "generated.ts");

const defaults = await readPromptFiles(defaultsDir);
const overrides = await readPromptFiles(overridesDir);

for (const id of overrides.keys()) {
  if (!defaults.has(id)) {
    throw new Error(`Prompt override has no matching default: ${id}`);
  }
}

const prompts = new Map(defaults);
for (const [id, content] of overrides.entries()) {
  prompts.set(id, content);
}

const sources = new Map(
  [...prompts.keys()].map((id) => [id, overrides.has(id) ? "override" : "default"])
);

const output = [
  "// Auto-generated by scripts/build-prompts.mjs. Do not edit.",
  "",
  "export const GENERATED_PROMPTS = {",
  ...[...prompts.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .flatMap(([id, content]) => [
      `  ${JSON.stringify(id)}: {`,
      `    id: ${JSON.stringify(id)},`,
      `    content: ${JSON.stringify(content)},`,
      `    source: ${JSON.stringify(sources.get(id))},`,
      `    checksum: ${JSON.stringify(sha256(content))}`,
      "  },"
    ]),
  "} as const;",
  ""
].join("\n");

await writeFile(outputPath, output, "utf8");

async function readPromptFiles(directory) {
  const files = await listMarkdownFiles(directory);
  const prompts = new Map();

  for (const file of files) {
    const relativePath = path.relative(directory, file).split(path.sep).join("/");
    const id = relativePath.replace(/\.md$/u, "");
    prompts.set(id, normalizePromptContent(await readFile(file, "utf8")));
  }

  return prompts;
}

async function listMarkdownFiles(directory) {
  await mkdir(directory, { recursive: true });
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        return listMarkdownFiles(fullPath);
      }
      return entry.isFile() && entry.name.endsWith(".md") ? [fullPath] : [];
    })
  );

  return files.flat();
}

function normalizePromptContent(content) {
  return `${content.replace(/\r\n/g, "\n").trimEnd()}\n`;
}

function sha256(content) {
  return createHash("sha256").update(content).digest("hex");
}
